server.port: 8066

tgbot:
    name: MEME_POLICE_BOT
    token: ${TG_BOT_TOKEN}
    channel: -1001261743202
    channelName: Meme Police

vkbot:
    name: MEME_POLICE_BOT
    token: ${VK_BOT_TOKEN}
    appid: ${VK_BOT_ID}
    groupId: ${VK_GROUP_ID}
    groupToken: ${VK_GROUP_TOKEN}
    conferenceId: ${VK_CONFERENCE_ID}

